## QUIZ 
- Dayana Valentina Gonzalez Vargas

# LIBRERÍAS

In [ ]:
import numpy as np

### ARBOL BINARIO

In [ ]:
class Tree_binary:
  def __init__(self, data):
    self.data = data 
    self.left = None
    self.right = None

def Insert_Sort_Event(raiz,punto):
    if(raiz.data[1] < punto.data[1]):
        if raiz.left is None:
            raiz.left = punto
        else:
            Insert_Sort_Event(raiz.left,punto)
    elif(raiz.data[1] == punto.data[1]):
        if(raiz.data[0] > punto.data[0]):
            if raiz.left is None:
                raiz.left = punto
            else:
                Insert_Sort_Event(raiz.left,punto)
        else:
            if raiz.right is None:
                raiz.right = punto
            else:
                Insert_Sort_Event(raiz.right,punto)
    else:
        if raiz.right is None:
                raiz.right = punto
        else:
            Insert_Sort_Event(raiz.right,punto) 

In [ ]:
def inorder(root):
    inorderArr = []
    if root.left is not None:
        leftInorderArr = inorder(root.left)
        inorderArr.extend(leftInorderArr) 
    
    inorderArr.append(root.data)
    if root.right is not None:
        rightInorderArr = inorder(root.right)
        inorderArr.extend(rightInorderArr) 
    
    return inorderArr

In [ ]:
#pruebas
root = Tree_binary([4,4])
arr = [[1,2],[3,4],[4,5],[2,2]]
for i in range(len(arr)):
  Insert_Sort_Event(root,Tree_binary(arr[i]))
print(root.left.data)
print(root.right.data)
inorder(root)

[3, 4]
[1, 2]


[[4, 5], [3, 4], [4, 4], [1, 2], [2, 2]]

## RESULTADO FINAL

In [ ]:
P = np.round(np.random.rand(20,2),2)
#definieremos un punto inicial como la raiz
print("Puntos iniciales:", P)
root2 = Tree_binary(P[0])
print("La raiz inicial es:", root2.data)
for i in range(1,len(P)-1):
  Insert_Sort_Event(root2,Tree_binary(P[i]))



print('El arreglo obtenido a partir del arbol es:')
inorder(root2)

Puntos iniciales: [[0.91 0.14]
 [1.   0.52]
 [0.08 0.26]
 [0.22 0.48]
 [0.86 0.06]
 [0.52 0.56]
 [0.18 0.78]
 [0.07 0.54]
 [0.7  0.45]
 [0.7  0.18]
 [0.34 0.49]
 [0.88 0.29]
 [0.51 0.19]
 [0.22 0.91]
 [0.76 0.04]
 [0.34 0.04]
 [0.53 0.32]
 [1.   0.89]
 [0.35 0.53]
 [0.55 0.44]]
La raiz inicial es: [0.91 0.14]
El arreglo obtenido a partir del arbol es:


[array([0.22, 0.91]),
 array([1.  , 0.89]),
 array([0.18, 0.78]),
 array([0.52, 0.56]),
 array([0.07, 0.54]),
 array([0.35, 0.53]),
 array([1.  , 0.52]),
 array([0.34, 0.49]),
 array([0.22, 0.48]),
 array([0.7 , 0.45]),
 array([0.53, 0.32]),
 array([0.88, 0.29]),
 array([0.08, 0.26]),
 array([0.51, 0.19]),
 array([0.7 , 0.18]),
 array([0.91, 0.14]),
 array([0.86, 0.06]),
 array([0.34, 0.04]),
 array([0.76, 0.04])]